<template>
  <div id="app">
  <vHeader/>
  <headerNavbar/>
  <imgHeader/>
  <vCollection/>
  <lookCollection/>
  <Arrials/>
  <brand/>
  <infoFooter/>
  <theRights/>
  </div>
</template>


<script>

import  headerNavbar from './components/headerNavbar'
import  vHeader from './components/header'
import  imgHeader from './components/headerImg'
import vCollection  from './components/collection'
import lookCollection from './components/lookCollection'
import Arrials from './components/newArrivals'
import brand from './components/brands'
import infoFooter from './components/footer'
import theRights from './components/theRights'
export default {
  name: '#app',
  components: {
    vHeader,
     headerNavbar,
     imgHeader,
     vCollection,
     lookCollection,
     Arrials,
     brand,
     infoFooter,
     theRights
  }
}
</script>

<style lang="scss">

body::-webkit-scrollbar {
  width: 1em;
  background: #0F0F0F;
  /* display: none; */
}
 
body::-webkit-scrollbar-track {
  box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
}
 
body::-webkit-scrollbar-thumb {
  background-color: darkgrey;
  outline: 1px solid slategrey;
}



@font-face {
	font-family: 'Post No Bills Jaffna';
	src: url('./assets/fonts/Post No Bills Jaffna/fonts/PostNoBillsJaffna-Bold.eot');
  src: local('☺'), url('./assets/fonts/Post No Bills Jaffna/fonts/PostNoBillsJaffna-Bold.woff') 
  format('woff'), url('./assets/fonts/Post No Bills Jaffna/fonts/PostNoBillsJaffna-Bold.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}

/** Generated by FG **/
@font-face {
	font-family: 'PT Sans';
	src: url('./assets/fonts/PT Sans/fonts/PTS55F.eot');
  src: local('☺'), url('./assets/fonts/PT Sans/fonts/PTS55F.woff') format('woff'),
   url('./assets/fonts/PT Sans/fonts/PTS55F.ttf') format('truetype'), url('./assets/fonts/PT Sans/fonts/PTS55F.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}

/** Generated by FG **/
@font-face {
	font-family: 'Playfair Display';
	src: url('./assets/fonts/PlayfairDisplayRegular/fonts/PlayfairDisplayRegular.eot');
	src: local('☺'), url('./assets/fonts/PlayfairDisplayRegular/fonts/PlayfairDisplayRegular.woff') 
  format('woff'), url('./assets/fonts/PlayfairDisplayRegular/fonts/PlayfairDisplayRegular.ttf')
 format('truetype'), url('./assets/fonts/PlayfairDisplayRegular/fonts/PlayfairDisplayRegular.svg') format('svg');
	font-weight: normal;
	font-style: normal;
}





*{
  width: 100%;
  height: auto;
  overflow-x: hidden;
  box-sizing: border-box;
  padding: 0;
  margin: 0;
  text-decoration: none;
  outline: none;
}
</style>
